//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcarAkademiRehberlik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Meeting_Book_Recommendation = new HashSet<Meeting_Book_Recommendation>();
        }
    
        public int book_id { get; set; }
        public string bookName { get; set; }
        public string examArea { get; set; }
        public string bookType { get; set; }
        public string author { get; set; }
        public string bookClass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting_Book_Recommendation> Meeting_Book_Recommendation { get; set; }
    }
}
