//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcarAkademiRehberlik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting_Book_Recommendation
    {
        public int Meeting_Book_Recommendation_Id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> book_id { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Student Student { get; set; }
    }
}
