//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcarAkademiRehberlik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Attendance = new HashSet<Attendance>();
            this.Meeting = new HashSet<Meeting>();
            this.Meeting_Book_Recommendation = new HashSet<Meeting_Book_Recommendation>();
        }
    
        public int student_id { get; set; }
        public string name { get; set; }
        public string @class { get; set; }
        public string school { get; set; }
        public string phoneNumber { get; set; }
        public Nullable<double> yksScore { get; set; }
        public Nullable<double> tytScore { get; set; }
        public Nullable<double> aytScore { get; set; }
        public Nullable<double> msuScore { get; set; }
        public string purpose { get; set; }
        public string parent1Name { get; set; }
        public string parent1ParentalCloseness { get; set; }
        public string parent1PhoneNumber { get; set; }
        public string parent2Name { get; set; }
        public string parent2ParentalCloseness { get; set; }
        public string parent2PhoneNumber { get; set; }
        public Nullable<int> teacher_id { get; set; }
        public Nullable<double> homework_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting> Meeting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting_Book_Recommendation> Meeting_Book_Recommendation { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
